### ISSUE TITLE
Game crashes when I enter level

### ISSUE THREAD

**Issue by legowiifun** [adafcaefc/Geome3Dash#5]
When I enter a level or enter the world screen with the mod enabled, the game crashes. Here is the crashlog: 
[2024-12-09_11-42-40.txt](https://github.com/user-attachments/files/18066447/2024-12-09_11-42-40.txt)

**Comment by adafcaefc** [comment]
I think this is fixed on the developmental release
https://github.com/adafcaefc/Geome3Dash/releases/tag/develop

**Comment by legowiifun** [comment]
It unfortunately is not fixed: 
[2024-12-10_11-40-40.txt](https://github.com/user-attachments/files/18084418/2024-12-10_11-40-40.txt)

**Comment by adafcaefc** [comment]
I will take a look on this, for now try disabling some mods
